export const ERC721_ABI = [
  'function balanceOf(address _owner) public view returns (uint256)',
  'function ownerOf(uint256 _tokenId) public view returns (address)',
  'function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) public payable',
  'function transferFrom(address _from, address _to, uint256 _tokenId) public payable',
  'function approve(address _approved, uint256 _tokenId) public payable',
  'function setApprovalForAll(address _operator, bool _approved) public',
  'function getApproved(uint256 _tokenId) public view returns (address)',
  'function isApprovedForAll(address _owner, address _operator) public view returns (bool)',
  'function supportsInterface(bytes4 interfaceID) public view returns (bool)',
  'function onERC721Received(address _operator, address _from, uint256 _tokenId, bytes _data) public returns(bytes4)',
  'function name() public view returns (string _name)',
  'function symbol() public view returns (string _symbol)',
  'function totalSupply() public view returns (uint256)',
  'function tokenURI(uint256 _tokenId) public view returns (string)',
  'function tokenByIndex(uint256 _index) public view returns (uint256)',
  'function tokenOfOwnerByIndex(address _owner, uint256 _index) public view returns (uint256)',
  'event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId)',
  'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
  'event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId)',
];
